#!/usr/bin/env perl

use strict;
use warnings;
use IO::Pipe;
use POSIX qw/strftime/;

sleep 1 while eval { loop() };

sub loop {

    print "listening for remote growl clients...\n";
    die "$!" unless
    my $nc = IO::Pipe->new->reader(qw/ nc -vkl 12340 /);

    while ( my $line = $nc->getline ) {

        chomp(
          my ($host, $message) = split /\0/, $line
        );

        system growlnotify => '-t', $host, '-m', $message;

        printf "[%s] $host -> $message\n", strftime('%F %T', localtime);
    }
}
